### ISSUE TITLE
MVP- Search Bar component

### ISSUE THREAD

**Issue by alivaditis** [mbenfowler/sound-stash#10]
As a user I should see a search bar component under the header at all times.  Upon typing and clicking search or pressing enter, I should see a page of results.  Results are a list of cards, a card has a title, artist name, and an cover img.

**Comment by jmartin777** [comment]
User Implications
1.The user sees a search bar component located under the header of the application at all times, allowing them to perform music searches easily.

2.The user enters their desired search query (e.g., song title, artist name, album name) into the search bar.

3. After typing the search query, the user clicks the search button or presses the Enter key to initiate the search.
